import Head from "next/head";
import { BitGo } from "bitgo";

export default function Home() {
  const sdk = new BitGo({ env: "test" });

  console.log("sdk", sdk);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>BitGoJS SDK</p>
        <p>Current Environment: {sdk.env}</p>
      </main>
    </div>
  );
}
