import Head from "next/head";
import { bitgo } from '~/services/bitgo';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>BitGoJS SDK</p>
        <p>Current Environment: {bitgo.env}</p>
      </main>
    </div>
  );
}
